### ISSUE TITLE
Yolo4 Example not clear to understand.

### ISSUE THREAD

**Issue by MyraBaba** [yhsmiley/bytetrack_realtime#5]
Hi @yhsmiley 

I couldnt figure out the example usage. 

I have the csv file x,y,w,h with scores for all frames  . 

How am I going to submit this x,y,w,h arrays to the tracker and saw trackID on the screen ? 

Yolo4 Example not clear to understand.

Please kindly give an example of submitting list of x,y,w,h with scores 

Best

**Comment by yhsmiley** [comment]
The example is meant for use on a video stream. The documentation for `detect_get_box_in` function can be seen [here](https://github.com/yhsmiley/ScaledYOLOv4/blob/8b21664888c0604e7ba0e9f146af0e7d6f3c4121/scaledyolov4/scaled_yolov4.py#L105). Since you already have the detections, you can format them into a list of ndarray for each frame, and pass them into the `update_tracks` function.
